### PR TITLE
minify script injection at build-time

### PR DESCRIPTION
**Pull request by Vijaykv5**
The script is minified and minified script is correctly injected into Nuxt project using useHead.

**Steps done :**

1. The provided script is defined as a string, with unnecessary whitespace removed using .replace(/\s+/g, ' ').

2. The script is then injected into the page using useHead, specifying the script tag's position, key, and innerHTML containing the script.

3. After running your build process, check the output directory in name of `script.min.js` in /dist  folder

/claim #3 

## Summary by CodeRabbit

- **New Features**
	- Introduced a new way to format dates based on user locale and specified options, enhancing date displays throughout the application.

### CODE REVIEW

**Comment by Vijaykv5** [comment]
@danielroe May you can review this PR?

Thanks!

**Review by danielroe — CHANGES_REQUESTED** [review]
This doesn't seem to use the minified script at all, just produces it in the dist directory.

**Comment by Vijaykv5** [comment]
This doesn't seem to use the minified script at all, just produces it in the dist directory.
you're right! @danielroe 
The current code only just minifies it & produce it dist folder.
I need that minified file to Inject in the `usehead` but currently its just using the script inside `/src/script` not the the minified one inside dist.
I'm new to Vue, May you can help me with it so we can resolve it.
Thanks!

**Comment by Vijaykv5** [comment]
> > This doesn't seem to use the minified script at all, just produces it in the dist directory.
> 
> @danielroe  you're right! The current code only just minifies it & produce it dist folder. I need that minified file to Inject in the `usehead` but currently its just using the script inside `/src/script` not the the minified one inside dist. I'm new to Vue, May you can help me with it so we can resolve it.

Thanks!

**Comment by Vijaykv5** [comment]
@danielroe May you can suggest me the best way to implement it please?

**Comment by danielroe** [comment]
I really appreciate your time on this. I've implemented it here - I hope that helps in future!

**Pull request closed without merging**
